import type { Metadata } from "next";
import { Fragment, ReactNode } from "react";

import { Header } from "@widgets/header";
import { UserProfile } from "@widgets/user-profile";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type MarketingLayoutProps = {
	children: ReactNode;
};

const MarketingLayout = ({ children }: Readonly<MarketingLayoutProps>) => {
	return (
		<Fragment>
			<Header className="relative z-50 mr-[2.5rem]">
				<UserProfile />
			</Header>
			<main className="z-50 flex-1">{children}</main>
		</Fragment>
	);
};

export default MarketingLayout;
