import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Suspense } from "react";

import { ChangeLog } from "@widgets/change-log";
import { MainNavigation } from "@widgets/main-navigation";
import { ProjectsNavigation } from "@widgets/projects-navigation";
import { Sidebar } from "@widgets/sidebar";
import { UserInfo, UserInfoSkeleton } from "@widgets/user-info";

import { CREATE_PROJECT_TRIGGER_VARIANTS, CreateProject } from "@features/create-project";

import { Background } from "@shared/ui";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type DashboardLayoutProps = {
	children: ReactNode;
};

const DashboardLayout = ({ children }: Readonly<DashboardLayoutProps>) => {
	return (
		<div className="grid min-h-0 grid-cols-[auto_1fr] grid-rows-[1fr] gap-x-[1.25rem] z-50 flex-1 shrink-0 bg-(--geek-blue-11)">
			<Sidebar>
				<Sidebar.Header>
					<Suspense fallback={<UserInfoSkeleton />}>
						<UserInfo />
					</Suspense>
				</Sidebar.Header>
				<Sidebar.Divider className="w-full" />
				<Sidebar.Content>
					<MainNavigation />
					<ProjectsNavigation>
						<ProjectsNavigation.Actions>
							<CreateProject.Trigger variant={CREATE_PROJECT_TRIGGER_VARIANTS.Icon} />
						</ProjectsNavigation.Actions>
					</ProjectsNavigation>
				</Sidebar.Content>
				<Sidebar.Footer>
					<ChangeLog />
				</Sidebar.Footer>
			</Sidebar>
			<main className="relative my-[0.75rem] mr-[0.75rem] flex min-h-0 min-w-0 flex-col overflow-hidden border-[0.031rem] border-solid border-(--white-pallete-10) rounded-[1.5rem] bg-(--white-pallete-50) p-[1.25rem]">
				<Background />
				{children}
			</main>
		</div>
	);
};

export default DashboardLayout;
